// # This file was auto-generated by generate_audio.py     # It defines a global constant MANIFEST used by index.html
window.MANIFEST = [
  {
    "number": 468,
    "file": "audio/n_468.mp3",
    "digits": 3
  },
  {
    "number": 15536,
    "file": "audio/n_15536.mp3",
    "digits": 5
  },
  {
    "number": 25,
    "file": "audio/n_25.mp3",
    "digits": 2
  },
  {
    "number": 45896,
    "file": "audio/n_45896.mp3",
    "digits": 5
  },
  {
    "number": 79817,
    "file": "audio/n_79817.mp3",
    "digits": 5
  },
  {
    "number": 11,
    "file": "audio/n_11.mp3",
    "digits": 2
  },
  {
    "number": 966,
    "file": "audio/n_966.mp3",
    "digits": 3
  },
  {
    "number": 92,
    "file": "audio/n_92.mp3",
    "digits": 2
  },
  {
    "number": 142,
    "file": "audio/n_142.mp3",
    "digits": 3
  },
  {
    "number": 820,
    "file": "audio/n_820.mp3",
    "digits": 3
  },
  {
    "number": 95,
    "file": "audio/n_95.mp3",
    "digits": 2
  },
  {
    "number": 51,
    "file": "audio/n_51.mp3",
    "digits": 2
  },
  {
    "number": 169,
    "file": "audio/n_169.mp3",
    "digits": 3
  },
  {
    "number": 63,
    "file": "audio/n_63.mp3",
    "digits": 2
  },
  {
    "number": 95384,
    "file": "audio/n_95384.mp3",
    "digits": 5
  },
  {
    "number": 53,
    "file": "audio/n_53.mp3",
    "digits": 2
  },
  {
    "number": 80,
    "file": "audio/n_80.mp3",
    "digits": 2
  },
  {
    "number": 49818,
    "file": "audio/n_49818.mp3",
    "digits": 5
  },
  {
    "number": 39811,
    "file": "audio/n_39811.mp3",
    "digits": 5
  },
  {
    "number": 84,
    "file": "audio/n_84.mp3",
    "digits": 2
  },
  {
    "number": 90916,
    "file": "audio/n_90916.mp3",
    "digits": 5
  },
  {
    "number": 962,
    "file": "audio/n_962.mp3",
    "digits": 3
  },
  {
    "number": 768,
    "file": "audio/n_768.mp3",
    "digits": 3
  },
  {
    "number": 34,
    "file": "audio/n_34.mp3",
    "digits": 2
  },
  {
    "number": 235,
    "file": "audio/n_235.mp3",
    "digits": 3
  },
  {
    "number": 74,
    "file": "audio/n_74.mp3",
    "digits": 2
  },
  {
    "number": 918,
    "file": "audio/n_918.mp3",
    "digits": 3
  },
  {
    "number": 66,
    "file": "audio/n_66.mp3",
    "digits": 2
  },
  {
    "number": 41,
    "file": "audio/n_41.mp3",
    "digits": 2
  },
  {
    "number": 88,
    "file": "audio/n_88.mp3",
    "digits": 2
  },
  {
    "number": 855,
    "file": "audio/n_855.mp3",
    "digits": 3
  },
  {
    "number": 752,
    "file": "audio/n_752.mp3",
    "digits": 3
  },
  {
    "number": 787,
    "file": "audio/n_787.mp3",
    "digits": 3
  },
  {
    "number": 73828,
    "file": "audio/n_73828.mp3",
    "digits": 5
  },
  {
    "number": 49996,
    "file": "audio/n_49996.mp3",
    "digits": 5
  },
  {
    "number": 253,
    "file": "audio/n_253.mp3",
    "digits": 3
  },
  {
    "number": 97,
    "file": "audio/n_97.mp3",
    "digits": 2
  },
  {
    "number": 659,
    "file": "audio/n_659.mp3",
    "digits": 3
  },
  {
    "number": 564,
    "file": "audio/n_564.mp3",
    "digits": 3
  },
  {
    "number": 51562,
    "file": "audio/n_51562.mp3",
    "digits": 5
  }
    {
    "number": 67,
    "file": "audio/n_67.mp3",
    "digits": 2
  },

];

