// # This file was auto-generated by generate_audio.py; it defines window.MANIFEST for index.html
window.MANIFEST = [
  {
    "number": 9018,
    "file": "audio/n_9018.mp3",
    "digits": 4
  },
  {
    "number": 814,
    "file": "audio/n_814.mp3",
    "digits": 3
  },
  {
    "number": 53,
    "file": "audio/n_53.mp3",
    "digits": 2
  },
  {
    "number": 49,
    "file": "audio/n_49.mp3",
    "digits": 2
  },
  {
    "number": 34251,
    "file": "audio/n_34251.mp3",
    "digits": 5
  },
  {
    "number": 944,
    "file": "audio/n_944.mp3",
    "digits": 3
  },
  {
    "number": 37,
    "file": "audio/n_37.mp3",
    "digits": 2
  },
  {
    "number": 9,
    "file": "audio/n_9.mp3",
    "digits": 1
  },
  {
    "number": 1059,
    "file": "audio/n_1059.mp3",
    "digits": 4
  },
  {
    "number": 4,
    "file": "audio/n_4.mp3",
    "digits": 1
  },
  {
    "number": 453,
    "file": "audio/n_453.mp3",
    "digits": 3
  },
  {
    "number": 77,
    "file": "audio/n_77.mp3",
    "digits": 2
  },
  {
    "number": 59,
    "file": "audio/n_59.mp3",
    "digits": 2
  },
  {
    "number": 961,
    "file": "audio/n_961.mp3",
    "digits": 3
  },
  {
    "number": 929,
    "file": "audio/n_929.mp3",
    "digits": 3
  },
  {
    "number": 373,
    "file": "audio/n_373.mp3",
    "digits": 3
  },
  {
    "number": 62131,
    "file": "audio/n_62131.mp3",
    "digits": 5
  },
  {
    "number": 6212,
    "file": "audio/n_6212.mp3",
    "digits": 4
  },
  {
    "number": 731,
    "file": "audio/n_731.mp3",
    "digits": 3
  },
  {
    "number": 61,
    "file": "audio/n_61.mp3",
    "digits": 2
  },
  {
    "number": 18,
    "file": "audio/n_18.mp3",
    "digits": 2
  },
  {
    "number": 988,
    "file": "audio/n_988.mp3",
    "digits": 3
  },
  {
    "number": 11,
    "file": "audio/n_11.mp3",
    "digits": 2
  },
  {
    "number": 4425,
    "file": "audio/n_4425.mp3",
    "digits": 4
  },
  {
    "number": 3900,
    "file": "audio/n_3900.mp3",
    "digits": 4
  },
  {
    "number": 56,
    "file": "audio/n_56.mp3",
    "digits": 2
  },
  {
    "number": 2,
    "file": "audio/n_2.mp3",
    "digits": 1
  },
  {
    "number": 6,
    "file": "audio/n_6.mp3",
    "digits": 1
  },
  {
    "number": 42590,
    "file": "audio/n_42590.mp3",
    "digits": 5
  },
  {
    "number": 660,
    "file": "audio/n_660.mp3",
    "digits": 3
  },
  {
    "number": 493,
    "file": "audio/n_493.mp3",
    "digits": 3
  },
  {
    "number": 93,
    "file": "audio/n_93.mp3",
    "digits": 2
  },
  {
    "number": 96,
    "file": "audio/n_96.mp3",
    "digits": 2
  },
  {
    "number": 2176,
    "file": "audio/n_2176.mp3",
    "digits": 4
  },
  {
    "number": 2852,
    "file": "audio/n_2852.mp3",
    "digits": 4
  },
  {
    "number": 25,
    "file": "audio/n_25.mp3",
    "digits": 2
  },
  {
    "number": 0,
    "file": "audio/n_0.mp3",
    "digits": 1
  },
  {
    "number": 7,
    "file": "audio/n_7.mp3",
    "digits": 1
  },
  {
    "number": 6243,
    "file": "audio/n_6243.mp3",
    "digits": 4
  },
  {
    "number": 16,
    "file": "audio/n_16.mp3",
    "digits": 2
  },
  {
    "number": 43,
    "file": "audio/n_43.mp3",
    "digits": 2
  },
  {
    "number": 182,
    "file": "audio/n_182.mp3",
    "digits": 3
  },
  {
    "number": 4176,
    "file": "audio/n_4176.mp3",
    "digits": 4
  },
  {
    "number": 58,
    "file": "audio/n_58.mp3",
    "digits": 2
  },
  {
    "number": 74,
    "file": "audio/n_74.mp3",
    "digits": 2
  },
  {
    "number": 1,
    "file": "audio/n_1.mp3",
    "digits": 1
  },
  {
    "number": 777,
    "file": "audio/n_777.mp3",
    "digits": 3
  },
  {
    "number": 72,
    "file": "audio/n_72.mp3",
    "digits": 2
  },
  {
    "number": 669,
    "file": "audio/n_669.mp3",
    "digits": 3
  },
  {
    "number": 66,
    "file": "audio/n_66.mp3",
    "digits": 2
  },
  {
    "number": 855,
    "file": "audio/n_855.mp3",
    "digits": 3
  },
  {
    "number": 909,
    "file": "audio/n_909.mp3",
    "digits": 3
  },
  {
    "number": 137,
    "file": "audio/n_137.mp3",
    "digits": 3
  },
  {
    "number": 406,
    "file": "audio/n_406.mp3",
    "digits": 3
  },
  {
    "number": 38796,
    "file": "audio/n_38796.mp3",
    "digits": 5
  },
  {
    "number": 60,
    "file": "audio/n_60.mp3",
    "digits": 2
  },
  {
    "number": 242,
    "file": "audio/n_242.mp3",
    "digits": 3
  },
  {
    "number": 394,
    "file": "audio/n_394.mp3",
    "digits": 3
  },
  {
    "number": 54,
    "file": "audio/n_54.mp3",
    "digits": 2
  },
  {
    "number": 736,
    "file": "audio/n_736.mp3",
    "digits": 3
  },
  {
    "number": 9906,
    "file": "audio/n_9906.mp3",
    "digits": 4
  },
  {
    "number": 913,
    "file": "audio/n_913.mp3",
    "digits": 3
  },
  {
    "number": 80,
    "file": "audio/n_80.mp3",
    "digits": 2
  },
  {
    "number": 991,
    "file": "audio/n_991.mp3",
    "digits": 3
  },
  {
    "number": 17889,
    "file": "audio/n_17889.mp3",
    "digits": 5
  },
  {
    "number": 396,
    "file": "audio/n_396.mp3",
    "digits": 3
  },
  {
    "number": 3,
    "file": "audio/n_3.mp3",
    "digits": 1
  },
  {
    "number": 7894,
    "file": "audio/n_7894.mp3",
    "digits": 4
  },
  {
    "number": 3869,
    "file": "audio/n_3869.mp3",
    "digits": 4
  },
  {
    "number": 55,
    "file": "audio/n_55.mp3",
    "digits": 2
  },
  {
    "number": 8,
    "file": "audio/n_8.mp3",
    "digits": 1
  },
  {
    "number": 23085,
    "file": "audio/n_23085.mp3",
    "digits": 5
  },
  {
    "number": 47,
    "file": "audio/n_47.mp3",
    "digits": 2
  },
  {
    "number": 235,
    "file": "audio/n_235.mp3",
    "digits": 3
  },
  {
    "number": 978,
    "file": "audio/n_978.mp3",
    "digits": 3
  },
  {
    "number": 61302,
    "file": "audio/n_61302.mp3",
    "digits": 5
  },
  {
    "number": 3891,
    "file": "audio/n_3891.mp3",
    "digits": 4
  },
  {
    "number": 51,
    "file": "audio/n_51.mp3",
    "digits": 2
  },
  {
    "number": 739,
    "file": "audio/n_739.mp3",
    "digits": 3
  },
  {
    "number": 78444,
    "file": "audio/n_78444.mp3",
    "digits": 5
  },
  {
    "number": 46,
    "file": "audio/n_46.mp3",
    "digits": 2
  },
  {
    "number": 72149,
    "file": "audio/n_72149.mp3",
    "digits": 5
  },
  {
    "number": 27598,
    "file": "audio/n_27598.mp3",
    "digits": 5
  },
  {
    "number": 76,
    "file": "audio/n_76.mp3",
    "digits": 2
  },
  {
    "number": 4686,
    "file": "audio/n_4686.mp3",
    "digits": 4
  },
  {
    "number": 75,
    "file": "audio/n_75.mp3",
    "digits": 2
  },
  {
    "number": 252,
    "file": "audio/n_252.mp3",
    "digits": 3
  },
  {
    "number": 21,
    "file": "audio/n_21.mp3",
    "digits": 2
  },
  {
    "number": 65,
    "file": "audio/n_65.mp3",
    "digits": 2
  },
  {
    "number": 683,
    "file": "audio/n_683.mp3",
    "digits": 3
  },
  {
    "number": 10,
    "file": "audio/n_10.mp3",
    "digits": 2
  },
  {
    "number": 977,
    "file": "audio/n_977.mp3",
    "digits": 3
  },
  {
    "number": 5,
    "file": "audio/n_5.mp3",
    "digits": 1
  },
  {
    "number": 444,
    "file": "audio/n_444.mp3",
    "digits": 3
  },
  {
    "number": 1578,
    "file": "audio/n_1578.mp3",
    "digits": 4
  }
];
